### ISSUE TITLE
如何自动编译

### ISSUE THREAD

**Issue by gpromote** [gpromote/GitHubBase#2]
如何在提交master或PR时进行自动编译？

**Comment by gpromote** [comment]
添加yml文件。路径：.github\workflows\dotnet-core.yml
```yml
name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./WebApplication/
    - name: Build
      run: dotnet build ./WebApplication/ --configuration Release --no-restore
    - name: Test
      run: dotnet test ./WebApplication/ --no-restore --verbosity normal

```
